### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by ghost** [TypecastException/ConsoleApplicationBase#4]
`const string _commandNamespace = "Console.Core.Commands";`

Adding another library and add the commands in there does not work please help.

**Comment by xivSolutions** [comment]
Can you show a little more code?

The program looks in the executing project assembly for a commands folder, and enumerates the classes it finds in that folder. See [here].(https://github.com/TypecastException/ConsoleApplicationBase/blob/master/ConsoleApplicationBase/Program.cs#L25)

**Comment by ghost** [comment]
Hi @xivSolutions 

Sorry late response what i ment is what if i want to throw the comands folder in library called Console.Core where Core is the library and console in the console lol. how would i allow this string below to look at the library(commands folder)

const string _commandNamespace = "Console.Core.Commands";

Core(Library)
Command(Folder in lib)

**Comment by xivSolutions** [comment]
Hmmm...

Sounds not too complicated. I'm headed to work now, but I'll investigate and get back to you soon as I have a minute. Haven;t messed with this code in a while, so gotta refresh lol!

**Comment by ghost** [comment]
@xivSolutions Hey man, thanks can i send you my source so you can see what im trying to do?

Maybe you can correct it from there with out messing around with your repro

**Comment by ghost** [comment]
@xivSolutions  Wondering if you could assist me with my project can invite you? its a just a small issue i need help with
